[versions]
interop-common = "3.11.0"
interop-gradle = "3.2.0"
mockk = "1.13.7"

[libraries]
interop-common = { module = "com.projectronin.interop:interop-common", version.ref = "interop-common" }
interop-commonJackson = { module = "com.projectronin.interop:interop-common-jackson", version.ref = "interop-common" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
interop-gradle-junit = { id = "com.projectronin.interop.gradle.junit", version.ref = "interop-gradle" }
interop-gradle-publish = { id = "com.projectronin.interop.gradle.publish", version.ref = "interop-gradle" }
interop-gradle-spring = { id = "com.projectronin.interop.gradle.spring", version.ref = "interop-gradle" }
interop-version-catalog = { id = "com.projectronin.interop.gradle.version-catalog-update", version.ref = "interop-gradle" }
