services:
  backfill-server:
    restart: on-failure
    image: interop-backfill-server:local
    ports:
      - "8080"
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://springuser:ThePassword@mysql-server:3306/backfill-db"
      AUTH0_AUDIENCE: "https://interop-backfill.dev.projectronin.io"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://mock-oauth2:8080/backfill"
    depends_on:
      mysql-server:
        condition: service_healthy

  mysql-server:
    restart: always
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306"
    expose:
      - "3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "springuser", "-pThePassword" ]
      timeout: 5s
      retries: 3

  mock-oauth2:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.4
    ports:
      - "8080"
    expose:
      - "8080"
    volumes:
      - ./:/host
    environment:
      - JSON_CONFIG_PATH=/host/mock-oauth2-config.json