name: Build and Push Image
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Tests ]
    types: [ completed ]
    branches: [ main ]

jobs:

  fetch-metadata:
    runs-on: oci-shared
    name: Fetch Project Version and other metadata
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Get version.
        id: get-version
        run: |
          VERSION=$(./gradlew currentVersion | awk '{ if(/Project version:/) { print $3; exit } }')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.get-version.outputs.version }}


  image-build-push:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: [ fetch-metadata ]
    name: Build and Push Image to Artifactory
    uses: projectronin/github/.github/workflows/image_push_nexus.yml@image_push_nexus/v2
    with:
      base-directory: ./interop-backfill-server
      image-tag: ${{ github.sha }},${{ needs.fetch-metadata.outputs.version }},latest
      build_boot_jar: true
    secrets:
      username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}


  deploy:
    uses: projectronin/ronin-charts/.github/workflows/deploy.yaml@deploy/v3
    needs: [ fetch-metadata, image-build-push ]
    with:
      environment: dev
      application: interop-backfill
      commit-sha: ${{ github.sha }}
      tag: ${{ needs.fetch-metadata.outputs.version }}
    secrets: inherit
