name: Create Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release'
        type: string
        required: true
        default: 'main'
      increment:
        description: 'Type of version increment to perform'
        type: choice
        required: true
        options:
          - Patch
          - Minor
          - Major
      skip_publish:
        description: 'Skip publishing (use if changelog failed)'
        type: boolean
        required: false
        default: false

env:
  ronin.release: true

jobs:
  tag:
    runs-on: oci-shared
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute build
        if: ${{ github.event.inputs.skip_publish == 'false' }}
        run: ./gradlew build

      - name: Axion Release
        id: release
        if: ${{ github.event.inputs.skip_publish == 'false' }}
        run: |
          ./gradlew release \
             -Prelease.versionIncrementer=increment${{ github.event.inputs.increment }} \
             -Prelease.customUsername=${{ github.actor }} \
             -Prelease.customPassword=${{ github.token }}

      - name: Get version.
        id: get-version
        run: |
          VERSION=$(./gradlew currentVersion | awk '{ if(/Project version:/) { print $3; exit } }' | cut -d\- -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

    outputs:
      tag: "v${{ steps.get-version.outputs.version }}"

  release:
    runs-on: oci-shared
    needs: tag
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "refs/tags/${{ needs.tag.outputs.tag }}"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish
        if: ${{ github.event.inputs.skip_publish == 'false' }}
        run: ./gradlew publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_MAVEN_USER }}
          NEXUS_TOKEN: ${{ secrets.NEXUS_MAVEN_TOKEN }}

      - name: Generate Changelog
        id: changelog
        uses: gandarez/changelog-action@v1.2.0

      - name: Generate Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.tag.outputs.tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          artifacts: "**/build/libs/*.jar"

  image-build-push:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: [ fetch-metadata ]
    name: Build and Push Image to Artifactory
    uses: projectronin/github/.github/workflows/image_push_nexus.yml@image_push_nexus/v2
    with:
      base-directory: ./interop-backfill-server
      image-tag: ${{ github.sha }},${{ needs.fetch-metadata.outputs.version }},latest
      build_boot_jar: true
    secrets:
      username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}

  deploy:
    uses: projectronin/ronin-charts/.github/workflows/deploy.yaml@deploy/v3
    needs: [ tag, release ]
    with:
      environment: dev
      application: interop-backfill
      commit-sha: ${{ github.sha }}
      tag: ${{ needs.tag.outputs.tag }}
    secrets: inherit